apiVersion: v1
kind: Service
metadata:
  name: svc-go-simple-http
  namespace: test-a
spec:
  ports:
  - name: svc-go-simple-http
    port: 8900
    targetPort: 8900
  selector:
    app: go-simple-http
  type: LoadBalancer